//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Syneo.Sod.Dal.Gatekeeper.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsCommunicationHierarchy
    {
        public int Id { get; set; }
        public Nullable<int> IdSodForms { get; set; }
        public Nullable<int> IdSodFormsChild { get; set; }
        public Nullable<int> IdSodDefinitionRoot { get; set; }
        public Nullable<int> IdSodDefinitionRootChild { get; set; }
        public string CustomLogic { get; set; }
    
        public virtual SodForm SodForm { get; set; }
        public virtual SodForm SodForm1 { get; set; }
        public virtual SodDefinitionRoot SodDefinitionRoot { get; set; }
        public virtual SodDefinitionRoot SodDefinitionRoot1 { get; set; }
    }
}
