//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Syneo.Sod.Dal.Gatekeeper.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SodForm()
        {
            this.FormsCommunicationHierarchies = new HashSet<FormsCommunicationHierarchy>();
            this.FormsCommunicationHierarchies1 = new HashSet<FormsCommunicationHierarchy>();
            this.ProceedingDecisions = new HashSet<ProceedingDecision>();
            this.StoreOfDataPerForms = new HashSet<StoreOfDataPerForm>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdSodDefinitionRoot { get; set; }
        public Nullable<int> IdSodFormElementChoice { get; set; }
        public Nullable<int> IdDbColumnTypes { get; set; }
        public Nullable<int> IdPriviledges { get; set; }
        public Nullable<int> IdPriviledgesSupervisor { get; set; }
        public Nullable<int> IdProceedingDecisions { get; set; }
        public string Comment { get; set; }
        public string Metadata { get; set; }
        public string Value { get; set; }
    
        public virtual DbColumnType DbColumnType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsCommunicationHierarchy> FormsCommunicationHierarchies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsCommunicationHierarchy> FormsCommunicationHierarchies1 { get; set; }
        public virtual Priviledge Priviledge { get; set; }
        public virtual Priviledge Priviledge1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProceedingDecision> ProceedingDecisions { get; set; }
        public virtual SodDefinitionRoot SodDefinitionRoot { get; set; }
        public virtual SodFormElementChoice SodFormElementChoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOfDataPerForm> StoreOfDataPerForms { get; set; }
    }
}
