//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Syneo.Sod.Dal.Gatekeeper.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodUsersPriviledge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SodUsersPriviledge()
        {
            this.ProceedingDecisions = new HashSet<ProceedingDecision>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdSodUsers { get; set; }
        public Nullable<int> IdPriviledges { get; set; }
    
        public virtual Priviledge Priviledge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProceedingDecision> ProceedingDecisions { get; set; }
        public virtual SodUser SodUser { get; set; }
    }
}
